language: python

install:
  # Get dependencies
  - pip install -r requirements.txt
  # Set up to run jupyter notebooks:
  - pip install jupyter_client
  - pip install ipykernel
  - pip install nbconvert

script:
  # Run the notebook:
  - jupyter nbconvert --ExecutePreprocessor.kernel_name=python
    --ExecutePreprocessor.timeout=600 --to notebook --execute MakeEventList.ipynb

# Finally, deploy the PDF by force-pushing to an otherwise empty
# orphan branch (ie one with no history).
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git checkout --orphan auto
    git rm -rf .
    git add -f EVENTS.md
    git -c user.name='travis' -c user.email='travis' commit -m "pushed the latest event list, scraped from the Google calendar"
    git push -q -f https://drphilmarshall:$GITHUB_API_KEY@github.com/LSSTDESC/CosmologyMeetings auto
  fi
