theme: jekyll-theme-dinky

# Help on customizing dinky-themed github-pages sites: 
# https://github.com/pages-themes/dinky

title: [Cosmology Meetings]
# description: [A short description of your site's purpose]
